#Setup ~~~
#Follow these 2 steps to set up your site.

#Step 1: give your study group a name and a short description:
title: UMD R User Group
description: "An R user group for the University of Maryland community."

#Step 2: press the green 'Commit Changes' button at the bottom of this page.

# That's it, your website is all set up!
# You can see it at https://YourUserName.github.io/studyGroup/
# No need to change anything below this line.
# To make your first event, check out the instructions at https://github.com/mozillascience/studyGroup#how-to-launch-a-new-event
# Having trouble? Open a new issue at https://github.com/mozillascience/studyGroup/issues and we'll help you out ASAP!

# Optional Configuration
# None of these things need to be changed - but feel free!

# titleBackground: "https://s3-us-west-2.amazonaws.com/webmaker-kits/learning%402x.jpg"
titleBackground: "https://upload.wikimedia.org/wikipedia/commons/f/f1/McKeldin_Library%2C_front_view%2C_mid-afternoon_light%2C_August_21%2C_2006.jpg"
headlineSmall: "Welcome To The UMD R User Group!"
headlineMain: "Let's Hack Together"


#========================================
# No touching anything below this line :)
#========================================
# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503
  secondary-dark: 333

# Build settings
markdown: kramdown
permalink: pretty
