#Setup ~~~
#Follow these steps to set up your site.

#Step 1: change YourUserName to your username on GitHub:
baseurl: http://billmills.github.io/studyGroupTemplate/

#Step 2: give your study group a name and a short description:
title: MMCU Python Study Group
description: "A Python Study Group at MMCU."

#Step 3: cut and paste the address of the repository you forked here:
repourl: https://github.com/BillMills/studyGroupTemplate













# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503
  secondary-dark: 333

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/billdoesphysics
  - title: github
    url: https://github.com/BillMills/studyGroupTemplate

# Postal address (add as many lines as necessary)
#address:
#  - line: 3481 Melrose Place
#  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
